routes/web.php
<?php


//RUTA BASICA
      // Route::get('prueba', function(){
      //     return 'BIENVENIDO A RUTA DE PRUEBA';
      // });
//RUTA POR PARAMETROS
      // Route::get('nombre/{nombre}', function($nombre){
      //   return "Mi nombre es: ". $nombre;
      // });
// RUTA POR PARAMETROS CON VALOR POR DEFECTO
    // Route::get('usuario/{name?}', function($name = 'LordSystem'){
    //       return "Tu nombre es: ". $name;
    // });
//RUTAS Front
Route::get('/', 'FrontController@index');
Route::get('contacto', 'FrontController@contacto');
Route::get('reviews', 'FrontController@reviews');
Route::resource('genero', 'GeneresController');
Route::resource('mail', 'MailController');


//RUTAS DEL ADMIN
Auth::routes();
Route::group(['middleware' => ['auth','admin']], function(){
        Route::get('admin', 'FrontController@admin');
        Route::resource('movie', 'MovieController');
        Route::get('movie/{id}/destroy',[
          'uses' => 'MovieController@destroy',
          'as' => 'movie.destroy'
        ]);
        Route::resource('users', 'UsersController');
        Route::get('users/{id}/destroy',[
          'uses' => 'UsersController@destroy',
          'as' => 'users.destroy'
        ]);
        Route::get('generos', 'GeneresController@listing');
        Route::get('genero/{id}/destroy',[
          'uses' => 'GeneresController@destroy',
          'as' => 'generes.destroy'
        ]);

  });

//Route::get('/home', 'HomeController@index')->name('home');

app/Movie.php
<?php

namespace App;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use DB;
class Movie extends Model
{
    protected $table = "movies";

    protected $fillable = [
        'name','cast','direction','duration','path','genere_id'
    ];
    public function setPathAttribute($path){
      if(!empty($path)){
    		$name = Carbon::now()->second.$path->getClientOriginalName();
    		$this->attributes['path'] = $name;
    		\Storage::disk('public')->put($name, \File::get($path));
    }
  }
    public static function Movies(){
      return DB::table('movies')
      ->join('generes', 'generes.id', '=', 'movies.genere_id')
      ->select('movies.*', 'generes.genere')
      ->get();
    }
    public function genere(){
        return $this->belongsTo('App\Genere');
    }
}

resources/views/movie/create.blade.php
@extends('templates.admin')
@section('title', 'Registrar Pelicula')
@section('content')
{!! Form::open(['route' => 'movie.store', 'method' => 'POST','files'=>'true'])!!}  
    @include('movie.partials.form_create')
    {!!Form::submit('Registrar',['class'=>'btn btn-primary'])!!}
  {!!Form::close()!!}    
@endsection

resources/views/movie/edit.blade.php
@extends('templates.admin')
@section('title', 'Registrar Pelicula')
@section('content')
  {!! Form::model($movie,['route' => ['movie.update',$movie->id],'method' => 'PUT','files'=>'true'])!!}
      @include('movie.partials.form_create')
    {!!Form::submit('Actualizar',['class'=>'btn btn-primary'])!!}
  {!!Form::close()!!}

@endsection

resources/views/movie/index.blade.php
@extends('templates.admin')
@section('title', 'Lista Usuarios')
@section('content')
<table class="table table-striped">
  <thead>
    <th>Nombre</th>
    <th>Genero</th>
    <th>Direccion</th>
    <th>Caratula</th>
    <th>Operaciones</th>
  </thead>
    @foreach($movies as $movie)
      <tbody>
        <td>{{ $movie->name }}</td>
        <td>{{ $movie->genere->genere }}</td>
        <td>{{ $movie->direction }}</td>
        <td>

          <img src="movies/{{ $movie->path }}" alt="" style="width:100px">

        </td>
        <td>
        <a href="{{ route('movie.edit', $movie->id) }}" class="btn btn-warning"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></a>

        <a href="{{ route('movie.destroy', $movie->id) }}" onclick="return confirm('¿Seguro que deseas eliminarlo?')" class="btn btn-danger"><span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span></a>
      </td>
      </tbody>
   @endforeach
</table>
{!!$movies->render()!!}
@endsection