routes/web.php
<?php


//RUTA BASICA
      // Route::get('prueba', function(){
      //     return 'BIENVENIDO A RUTA DE PRUEBA';
      // });
//RUTA POR PARAMETROS
      // Route::get('nombre/{nombre}', function($nombre){
      //   return "Mi nombre es: ". $nombre;
      // });
// RUTA POR PARAMETROS CON VALOR POR DEFECTO
    // Route::get('usuario/{name?}', function($name = 'LordSystem'){
    //       return "Tu nombre es: ". $name;
    // });
//RUTAS Front
Route::get('/', 'FrontController@index');
Route::get('contacto', 'FrontController@contacto');
Route::get('reviews', 'FrontController@reviews');
Route::resource('genero', 'GeneresController');
Route::resource('mail', 'MailController');


//RUTAS DEL ADMIN
Auth::routes();
Route::group(['middleware' => ['auth','admin']], function(){
        Route::get('admin', 'FrontController@admin');
        Route::resource('movie', 'MovieController');
        Route::get('movie/{id}/destroy',[
          'uses' => 'MovieController@destroy',
          'as' => 'movie.destroy'
        ]);
        Route::resource('users', 'UsersController');
        Route::get('users/{id}/destroy',[
          'uses' => 'UsersController@destroy',
          'as' => 'users.destroy'
        ]);
        Route::get('generos', 'GeneresController@listing');
        Route::get('genero/{id}/destroy',[
          'uses' => 'GeneresController@destroy',
          'as' => 'generes.destroy'
        ]);

  });

//Route::get('/home', 'HomeController@index')->name('home');

resources/views/genero/create.blade.php
@extends('templates.admin')
  @section('title','Crear Genero')



@section('content')

    {!!Form::open()!!}

      <input type="hidden" name="_token" value="{{ csrf_token() }}" id="token">
        @include('genero.form.genero')
          {!!link_to("#", $title='Registrar', $attributes = ['id'=>'registro',
            'class'=>'btn btn-primary col-md-3 col-md-offset-5'], $secure= null)!!}


    {!!Form::close()!!}
@endsection

  @section('scripts')
    <script src="{{ asset('js/acciones_genero.js') }}"></script>
  @endsection

resources/views/genero/index.blade.php
@extends('templates.admin')
  @section('title','Lista de Generos')


    @section('content')
      @include('genero.modal')
      <a href="{{ route('genero.create') }}" class="btn btn-info">Registrar Nuevo Genero</a><hr>

        <table class="table table-striped">
            <thead>
              <th>Nombre</th>
              <th>Acciones</th>
            </thead>
            <tbody id="datos">

            </tbody>
        </table>

    @endsection
    @section('scripts')
      <script src="{{ asset('js/acciones_genero.js') }}"></script>
    @endsection

resources/views/genero/modal.blade.php
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Actualizar Genero</h4>
              </div>
              <div class="modal-body">

                <input type="hidden" name="_token" value="{{ csrf_token() }}" id="token">
                <input type="hidden" id="id">
                @include('genero.form.genero')
              </div>
              <div class="modal-footer">
              {!!link_to('#', $title='Actualizar', $attributes = ['id'=>'actualizar', 'class'=>'btn btn-primary'], $secure = null)!!}
              </div>
          </div>
      </div>
</div>